model: "UnetTest"
dataset: "Polyp"
classes: 1
img_loc: ['data/Kvasir-SEG/images', 'data/CVC-ClinicDB_png/Original']
mask_loc: ['data/Kvasir-SEG/masks', 'data/CVC-ClinicDB_png/Ground Truth']
bbox_loc: None
transform: None
train_ratio: 0.80
validation_ratio: 0.10
test_ratio: 0.10
batch_size: 5
epochs: 5
loss: "Cross Entropy"
optimizer: "Adam"
lr: 0.001
scheduler: None
scheduler_params: None
height: 256
width: 256
model_name: None  # *.pt file to save