# create a basic fusion network here
# want to fuse 2 different models
# possibly we will want to fuse more than 2?
# what if we fused two different models? take advantage of different things...
#   ex: fuse freiburg and ESANet to get good indoor and outdoor performance...